### ISSUE TITLE
3C BPT Futures history enhancement

### ISSUE THREAD

**Issue by derrey** [JeeZues/TradeBot#5]
I have been testing the new feature and it is just crushing all the other accounts I have been testing it against. (By nearly double)
My thought is to have the ability to add a new random to the of the top XX from that group. This will allow us to scale this up without all the accounts having the exact same trades open. The issue can be if you have all the same pairs open you could get trapped in a bad pair deal in all of them and could liquidate them all rather than just a few. This would still get the high volume signals and try to avoid duplicate accounts.

example: --signal_top_pairs_rnd 50

**Comment by JeeZues** [comment]
ok, let's walk through an example.  Currently I have ~60 pairs in a $4k account.  Running on good days at around 150%($375/deal), which is around 11 deals.  To get 11 deals, I start 5 bots (default is 3) per needed positions.  That would be 55 bots running.  In this case any top/random logic would make very little difference.
As well, if we were to randomize the top list, we need to do that for the top number of elements in that list, which I assume the 50 in your example refers to.
It's not much work to add.  Keep the issue open and I'll try to get to it this weekend since weather does not seem to be nice :)

**Comment by derrey** [comment]
> ok, let's walk through an example. Currently I have ~60 pairs in a $4k account. Running on good days at around 150%($375/deal), which is around 11 deals. To get 11 deals, I start 5 bots (default is 3) per needed positions. That would be 55 bots running. In this case any top/random logic would make very little difference.
> As well, if we were to randomize the top list, we need to do that for the top number of elements in that list, which I assume the 50 in your example refers to.
> It's not much work to add. Keep the issue open and I'll try to get to it this weekend since weather does not seem to be nice :)

My example is:

Create a standard set of all 107 pairs the BPT is using at this time and use it as a base to copy using BotManager to new accounts. Then use some accounts with the --signal_top_pairs and others with --signal_top_pairs_rnd 50. This will allow us to create and manage many futures accounts with 5K in each. Maybe 30-40 accounts. This will avoid all accounts having the same pairs opening and allows for much more diversification.

**Comment by JeeZues** [comment]
New `--signal_top_pairs_rnd n` argument added

**Comment by derrey** [comment]
I think that both are good settings.. one with standard order and one with random.. that will work well for different people.
Testing and will close for now.
